package veterinaria.Vistas;

// Importaciones de clases necesarias
import veterinaria.Entidades.Estado;
import veterinaria.DecimalDocumentFilter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import veterinaria.AccesoADatos.TratamientoDAO;
import veterinaria.CustomPanel;
import veterinaria.Entidades.Tratamiento;
import veterinaria.Utilidades;

// Definición de la clase FormularioTratamiento
public class FormularioTratamiento extends javax.swing.JInternalFrame {

    // Enumeración para el estado actual del formulario (NUEVO, BUSCAR, etc.)
    private Estado estado = Estado.NADA;

//    private Cliente selectedCliente = null;
//    private int idMascotas = 0;
//    private int idCliente = 0;
    private boolean estadoTratamiento;

    // Variable para almacenar el código del tratamiento
    private String codigo;

    /**
     * Constructor de la clase FormularioTratamiento.
     */
    public FormularioTratamiento() {
        // Configurar el panel personalizado
        CustomPanel customPanel = new CustomPanel();
        this.setContentPane(customPanel);

        // Inicializar los componentes del formulario
        initComponents();

        // Establecer el título del formulario
        setTitle("Cargar Tratamientos");

        // Obtener el Document asociado al campo de texto jTImporte y aplicar el DocumentFilter para reemplazar comas por puntos
        AbstractDocument doc = (AbstractDocument) jTImporte.getDocument();
        doc.setDocumentFilter(new DecimalDocumentFilter());
        // Agregar un KeyListener al campo de texto jTCodigo para manejar la tecla "Enter"
        jTCodigo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    // Método para procesar el código ingresado
                    codigo = Utilidades.obtenerTextoDesdeCampo(jTCodigo).trim();
                    if (codigo.isEmpty()) {
                        // Mostrar un mensaje si el campo de código está vacío
                        JOptionPane.showMessageDialog(null, "Debes escribir el Codigo");
                    } else {
                        // Limpiar y buscar el tratamiento asociado al código ingresado
                        limpiarBuscar();
                        estado = Estado.BUSCAR;
                        buscarxCodigo();
                    }
                }
            }
        });
        // Asociar tecla "Enter" con componentes
        asociarCamposConEnter();

        // Configurar ActionListener para el botón de estado
        configurarEstadoTratamiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLcodigo = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jTTipo = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLImporte = new javax.swing.JLabel();
        jTImporte = new javax.swing.JTextField();
        jRBEstado = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jBBuscar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setClosable(true);
        setNormalBounds(new java.awt.Rectangle(0, 0, 80, 0));
        setPreferredSize(new java.awt.Dimension(465, 410));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLcodigo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLcodigo.setText("Codigo");

        jTCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLTipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLTipo.setText("Tipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcodigo)
                    .addComponent(jLTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTTipo)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLcodigo)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipo)
                    .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLDescripcion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLDescripcion.setText("Descripcion");

        jTADescripcion.setColumns(20);
        jTADescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        jLImporte.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLImporte.setText("Importe");

        jTImporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jRBEstado.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jRBEstado.setText("Estado");
        jRBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jRBEstado)
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLImporte)
                    .addComponent(jRBEstado))
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/Imagenes/search_find_lupa_21889.png"))); // NOI18N
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/Imagenes/Save_37110.png"))); // NOI18N
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veterinaria/Imagenes/home256_24783.png"))); // NOI18N
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBuscar)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jBBuscar)
                .addGap(15, 15, 15)
                .addComponent(jBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalir)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getAccessibleContext().setAccessibleName("Formulario Tratamiento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEstadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRBEstadoActionPerformed
    /**
     * Método invocado cuando se hace clic en el botón "Buscar". Se encarga de
     * obtener el código ingresado, verificar que no esté vacío, limpiar el
     * formulario y luego realizar una búsqueda del tratamiento asociado al
     * código ingresado.
     *
     * @param evt Evento de acción generado por el botón "Buscar".
     */
    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // Obtener el código ingresado desde el campo de texto
        String codigo = jTCodigo.getText().trim();

        // Verificar si el campo de código está vacío
        if (codigo.isEmpty()) {
            // Mostrar un mensaje si el campo de código está vacío y salir del método
            JOptionPane.showMessageDialog(this, "Debes escribir un Codigo");
            return;
        } else {
            // Limpiar el formulario y establecer el estado como Búsqueda
            limpiarBuscar();
            estado = Estado.BUSCAR;

            // Realizar la búsqueda del tratamiento asociado al código ingresado
            buscarxCodigo();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarActionPerformed
    /**
     * Método invocado cuando se hace clic en el botón "Guardar". Se encarga de
     * validar los campos del formulario, guardar el tratamiento y luego limpiar
     * el formulario para permitir la entrada de nuevos datos.
     *
     * @param evt Evento de acción generado por el botón "Guardar".
     */
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            // Verificar si hay campos vacíos en el formulario
            if (camposVacios()) {
                // Mostrar un mensaje si hay campos vacíos y salir del método
                JOptionPane.showMessageDialog(this, "No debe dejar algún dato vacío");
            } else {
                // Llamar a la función guardar() para guardar el tratamiento
                guardar();

                // Limpiar el formulario después de guardar los datos
                limpiar();
            }
        } catch (Exception ex) {
            // Manejar cualquier excepción mostrando un mensaje de error
            Utilidades.mostrarError(ex, this);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed
    /**
     * Método invocado cuando se hace clic en el botón "Salir". Se encarga de
     * salir de la aplicación al invocar la función salirAplicacion().
     *
     * @param evt Evento de acción generado por el botón "Salir".
     */
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // Salir de la aplicación
        salirAplicacion();
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLImporte;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLcodigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTImporte;
    private javax.swing.JTextField jTTipo;
    // End of variables declaration//GEN-END:variables

    // Método para salir de la aplicación si el usuario confirma la salida
    private void salirAplicacion() {
        if (Utilidades.confirmarSalida(this)) {
            dispose();
        }
    }

    // Método para verificar si hay campos vacíos en el formulario
    private boolean camposVacios() {
        return jTTipo.getText().isEmpty() || jTCodigo.getText().isEmpty() || jTImporte.getText().isEmpty() || jTADescripcion.getText().trim().isEmpty();
    }

    // Método para limpiar los campos del formulario
    private void limpiar() {
        Utilidades.limpiarSetText(jTCodigo, jTTipo, jTImporte);
        jRBEstado.setSelected(false);
        jTADescripcion.setText("");
        estado = Estado.NADA;
    }

    // Método para limpiar los campos y deseleccionar los JComboBox del formulario
    private void limpiarBuscar() {
        Utilidades.limpiarSetText(jTTipo, jTImporte);
        jTADescripcion.setText("");
    }

    // Método para realizar la búsqueda del tratamiento por el código ingresado
    private void buscarxCodigo() {
        TratamientoDAO tratamientoD = TratamientoDAO.obtenerInstancia();
        int codigo = obtenerCodigoDesdeCampo();

        try {
            Tratamiento tratamiento = tratamientoD.buscarListaTratamientoxId(codigo);

            if (tratamiento != null) {
                configurarFormularioParaTratamientoExistente(tratamiento);
            } else {
                configurarFormularioParaNuevoTratamiento();
            }
        } catch (NumberFormatException e) {
            mostrarMensajeError("El código debe ser un número válido.");
        } catch (Exception ex) {
            Utilidades.mostrarError(ex, this);
        }
    }

    // Método para obtener el código desde el campo de texto y manejar posibles excepciones
    private int obtenerCodigoDesdeCampo() {
        try {
            return Integer.parseInt(jTCodigo.getText());
        } catch (NumberFormatException e) {
            mostrarMensajeError("Error: El código debe ser un número válido.");
            return 0;
        }
    }

    // Método para configurar el formulario cuando se encuentra un tratamiento existente
    private void configurarFormularioParaTratamientoExistente(Tratamiento tratamiento) {
        setTitle("Cargar Tratamiento" + (tratamiento.isEstado() ? "" : " -- Codigo dado de Baja"));
        jRBEstado.setSelected(tratamiento.isEstado());
        estado = Estado.BUSCAR;
        mostrarTratamientoEnFormulario(tratamiento);
    }

    // Método para configurar el formulario para un nuevo tratamiento
    private void configurarFormularioParaNuevoTratamiento() {
        try {
            estado = Estado.NUEVO;
            int ultimoCodigo = ultimoRegistro();
            jTCodigo.setText(ultimoCodigo + "");
            mostrarMensajeError("No se encontró el código, el código disponible es " + ultimoCodigo);
        } catch (Exception ex) {
            Logger.getLogger(FormularioTratamiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Método para mostrar un mensaje de error en un cuadro de diálogo
    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    // Método para guardar o modificar un tratamiento en la base de datos
    private void guardar() {
        try {
            int codigo = obtenerCodigoDesdeCampo(); // Obtiene el código del campo de texto
            TratamientoDAO tratamientoD = TratamientoDAO.obtenerInstancia(); // Obtiene la instancia del DAO de tratamiento
            Tratamiento tratamiento = tratamientoD.obtenerTratamientoxId(codigo); // Obtiene el tratamiento por el código

            // Verifica si el tratamiento ya existe y el estado es Nuevo
            if (tratamiento != null && estado.equals(Estado.NUEVO)) {
                mostrarMensajeError("El Codigo ya existe, no puede darlo de Alta.");
                return; // Muestra un mensaje y sale del método si el tratamiento ya existe y es Nuevo
            }

            //String tipo = jTTipo.getText(); // Obtiene el tipo del campo de texto
            //String descripcion = jTADescripcion.getText(); // Obtiene la descripción del campo de texto
            double importe = obtenerImporteDesdeCampo(); // Obtiene el importe del campo de texto
            boolean estadoMascota = jRBEstado.isSelected(); // Obtiene el estado del tratamiento desde el botón de radio

            // Crea un nuevo objeto Tratamiento con los datos del formulario
            tratamiento = new Tratamiento(
                    codigo,
                    Utilidades.obtenerTextoDesdeCampo(jTTipo),
                    Utilidades.obtenerTextoDesdeArea(jTADescripcion),
                    importe,
                    estadoMascota);

            tratamiento.setEstado(estadoMascota);

            // Guarda el tratamiento si el estado es Nuevo, o lo modifica si el estado es Búsqueda
            if (estado.equals(Estado.NUEVO)) {
                tratamiento.setEstado(true);
                tratamientoD.guardarTratamiento(tratamiento); // Guarda el tratamiento en la base de datos
            } else if (estado.equals(Estado.BUSCAR)) {
                tratamientoD.modificarTratamiento(tratamiento); // Modifica el tratamiento en la base de datos
            }

        } catch (NumberFormatException ex) {
            Utilidades.mostrarError(ex, this); // Maneja errores de formato de número mostrando un mensaje de error
        } catch (Exception ex) {
            Utilidades.mostrarError(ex, this); // Maneja otras excepciones mostrando un mensaje de error
        }
    }

    // Método para obtener el importe desde el campo de texto y manejar posibles excepciones
    private double obtenerImporteDesdeCampo() {
        try {
            return Double.parseDouble(jTImporte.getText()); // Parsea el importe y lo devuelve como un valor double
        } catch (NumberFormatException e) {
            mostrarMensajeError("Error: Debes ingresar un importe válido.");
            return 0.0; // Muestra un mensaje de error y devuelve 0.0 si el formato del importe no es válido
        }
    }

    // Método para obtener el último registro de la base de datos
    private int ultimoRegistro() throws Exception {
        TratamientoDAO tratamientoD = TratamientoDAO.obtenerInstancia(); // Obtiene la instancia del DAO de tratamiento
        return tratamientoD.contarTotalRegistros(); // Retorna el número total de registros en la base de datos

    }

    // Método para mostrar los detalles del tratamiento en el formulario
    private void mostrarTratamientoEnFormulario(Tratamiento tratamiento) {
        jTTipo.setText(tratamiento.getTipo()); // Establece el tipo del tratamiento en el campo de texto correspondiente
        jTADescripcion.setText(tratamiento.getDescripcion()); // Establece la descripción en el área de texto correspondiente
        jTImporte.setText(tratamiento.getImporte() + ""); // Establece el importe en el campo de texto correspondiente

        // Establece el título del formulario dependiendo del estado del tratamiento (Activo o dado de baja)
        if (tratamiento.isEstado()) {
            setTitle("Cargar Tratamiento"); // Si está activo, muestra el título como "Cargar Tratamiento"
        } else {
            setTitle("Tratamiento -- Codigo dado de Baja"); // Si está dado de baja, muestra el título con indicación
        }

        jRBEstado.setSelected(tratamiento.isEstado()); // Establece el estado del tratamiento en el botón de radio correspondiente
        estadoTratamiento = tratamiento.isEstado(); // Actualiza el estado del tratamiento en la variable de instancia
    }

    // Método para asociar la tecla Enter con componentes específicos
    private void asociarCamposConEnter() {
        // Utilidades.asociarEnterConComponente asocia la tecla Enter con el componente proporcionado como argumento  
        Utilidades.asociarEnterConComponente(jTCodigo, jTTipo);
        Utilidades.asociarEnterConComponente(jTTipo, jTADescripcion);
        Utilidades.asociarEnterConComponente(jTADescripcion, jTImporte);
        Utilidades.asociarEnterConComponente(jTImporte, jBBuscar);
    }

    // Método para configurar el cambio de estado de la mascota
    private void configurarEstadoTratamiento() {
        // Configura un ActionListener para el cambio de estado de la mascota 
        jRBEstado.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (estado.equals(Estado.BUSCAR)) {
                    confirmarCambioEstadoTratamiento();
                }
            }
        });
    }

    // Método para confirmar el cambio de estado del tratamiento
    private void confirmarCambioEstadoTratamiento() {
        //if (estado.equals(Estado.BUSCAR)) {
        int option = JOptionPane.showConfirmDialog(FormularioTratamiento.this,
                "¿Está seguro de cambiar el estado del Tratamiento?",
                "Confirmar Cambio de Estado",
                JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            int codigo = Integer.parseInt(jTCodigo.getText());
            TratamientoDAO tratamientoD = TratamientoDAO.obtenerInstancia();

            try {
                if (estadoTratamiento) {
                    tratamientoD.bajaLogica(codigo);
                    setTitle("Tratamiento -- Codigo dado de Baja");
                    JOptionPane.showMessageDialog(FormularioTratamiento.this, "El tratamiento ha sido dado de baja");
                } else {
                    tratamientoD.altaLogica(codigo);
                    setTitle("Mascota");
                    JOptionPane.showMessageDialog(FormularioTratamiento.this, "El tratamiento ha sido dado de alta");
                }
            } catch (Exception ex) {
                Utilidades.mostrarError(ex, FormularioTratamiento.this);
            }
        } else {
            jRBEstado.setSelected(!jRBEstado.isSelected());
        }
    }
}
